# Flutter CD configuration file with Cloud build

steps:

  # clone the latest source codes
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/Ekanth57/environments_in_flutter_with_codemagic.git']
    dir: '/workspace'

  # using flutter builder Docker image we have built previously to compile the repo
  - name: 'gcr.io/$PROJECT_ID/flutter'
    entrypoint: '/bin/bash'
    args: ['build.sh', '${_REPO_NAME}']
    
    https://console.cloud.google.com/artifacts/docker/parkon-300905/asia/cicd?project=parkon-300905
    
    
    # Push the APK file from vol1 to your GCS Bucket.
artifacts:
  objects:
    location: 'https://console.cloud.google.com/artifacts/docker/parkon-300905/asia/cicd?project=parkon-300905/'
    paths: ['*.apk']
    
    
    

#   # upload apk to google play store with Fastlane
#   - name: 'gcr.io/$PROJECT_ID/flutter'
#     args: ['supply', '--package_name','${_ANDROID_PACKAGE_NAME}', '--track', '${_ANDROID_RELEASE_CHANNEL}', '--json_key_data', '${_GOOGLE_PLAY_UPLOAD_KEY_JSON}', '--apk', '/workspace/${_REPO_NAME}/build/app/outputs/apk/release/app-release.apk']
# timeout: 1200s
